version: '3.8'
services:
  mariadb:
    image: mariadb:10.9
    env_file: .env
    ports: ["5000:3306"]
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/Dockerfile.backend
    env_file: .env
    ports: ["8000:8000"]
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports: ["5173:5173"] #vite default
    environment:
      - CHOKIDAR_USEPOLLING=true #could also include it in the .env file
      #Creating a .env file with CHOKIDAR_USEPOLLING=true worked for me (see stackoverflow.com/a/43281575/470749 and create-react-app.dev/docs/troubleshooting and stackoverflow.com/a/57691204/470749 ) – 
    command: npm run dev

volumes:
  db_data:
