version: '3.8'
services:
  postgres:
    container_name: postgresql
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit_network

  django:
    container_name: django
    build:
      context: . #look for dockerfile in the current directory
      dockerfile: Dockerfile #when using docker-compose up --build, it calls this file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    volumes:
      - .:/app #maps the host dir to the /app in the container
    depends_on:
      - postgres
    networks:
      - habit_network

volumes:
  postgres_data:

networks:
  habit_network:
    driver: bridge