# Generated by Django 5.1.4 on 2025-01-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_appusers_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('habit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('habit_name', models.CharField(max_length=40)),
                ('habit_action', models.CharField(max_length=120)),
                ('habit_streak', models.IntegerField(default=0)),
                ('habit_periodicity_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=7)),
                ('habit_periodicity_value', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_user_id', to='users.appusers')),
            ],
            options={
                'db_table': 'habits',
            },
        ),
    ]
