# Generated by Django 5.1.4 on 2025-01-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        ('users', '0003_alter_appusers_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='user_id',
        ),
        migrations.AddField(
            model_name='habits',
            name='habit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_habits', to='users.appusers'),
        ),
    ]
