# Generated by Django 5.1.4 on 2025-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habits_user_id_habits_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='habit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
