# Generated by Django 5.1.4 on 2025-01-18 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        ('kvi_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=50)),
                ('target_kvi_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current_kvi_value', models.FloatField(default=0.0)),
                ('goal_description', models.CharField(blank=True, max_length=80)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(blank=True, null=True)),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='habits.habits')),
                ('kvi_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='kvi_types.kvitypes')),
            ],
            options={
                'db_table': 'goals',
                'constraints': [models.UniqueConstraint(fields=('goal_name', 'habit_id'), name='unique_goal_for_habit_id')],
            },
        ),
    ]
