# Generated by Django 5.1.4 on 2025-01-18 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsersRoles',
            fields=[
                ('user_role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('bot', 'BOT')], max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_users_role',
            },
        ),
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(110)])),
                ('user_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.appusersroles')),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
