# Generated by Django 5.1.4 on 2025-03-21 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='user_password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='user_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(110)], verbose_name='User Age'),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.appusersroles', verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='appusersroles',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('bot', 'Bot')], max_length=10, primary_key=True, serialize=False, verbose_name='User Role'),
        ),
    ]
