# Generated by Django 5.1.4 on 2025-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appusers_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='user_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appusersroles',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('bot', 'BOT')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
