"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from apps.utils.env_manager import EnvManager
import sys


BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-xk)yb2(z(bohnac!a$povkdtgjk*c9uwhtstu&5g=5h88e%z^_'
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'apps.users',
	'apps.habits',
	'apps.kvi_types',
	'apps.goals',
	'apps.progresses',
	'apps.analytics',
	'apps.utils',
	'apps.database',
	'apps.core',
	'apps.notifications',
	'apps.reminders'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


config = EnvManager()
DATABASES = {
	"default": {
		"ENGINE": config.get_config("ENGINE"),
		"NAME": config.get_config("NAME"),
		"USER": config.get_config("USER"),
		"PASSWORD": config.get_config("PASSWORD"),
		"HOST": config.get_config("HOST"),
		"PORT": config.get_config("PORT")
	}
}

if 'test' in sys.argv:
	DATABASES['default'] = {
		"ENGINE": config.get_config("ENGINE"),
		'NAME': ':memory:',
	}

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
