"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from apps.utils.env_manager import EnvManager
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#get the env variables for database
# env = environ.Env()
# environ.Env.read_env(env_file=str(BASE_DIR / '.env'))  # Specify the .env path explicitly
# environ.Env.read_env() #FOR PRODUCTION COMMENT THIS OUT

# print(f"Host: {env('MARIADB_HOST')}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xk)yb2(z(bohnac!a$povkdtgjk*c9uwhtstu&5g=5h88e%z^_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'apps.users',
	'apps.habits',
	'apps.kvi_types',
	'apps.goals',
	'apps.progresses',
	'apps.analytics',
	'apps.utils',
	'apps.database',
	'apps.core',
	'apps.notifications'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
config = EnvManager() #singleton to store env details
DATABASES = {
	"default": {
		"ENGINE": config.get_config("ENGINE"),
		"NAME": config.get_config("NAME"),
		"USER": config.get_config("USER"),
		"PASSWORD": config.get_config("PASSWORD"),
		"HOST": config.get_config("HOST"),
		"PORT": config.get_config("PORT")
	}
}

# https://www.geeksforgeeks.org/how-to-run-django-s-test-using-in-memory-database/
if 'test' in sys.argv:
	DATABASES['default'] = {
		"ENGINE": config.get_config("ENGINE"),
		'NAME': ':memory:', #in memory database for pytest
	}
	
	# "default": {
	#     "ENGINE": "django.db.backends.mysql",
	#     "NAME": env("MARIADB_DATABASE"),
	#     "USER": env("MARIADB_USER"),  # Temporarily use root
	#     "PASSWORD": env("MARIADB_PASSWORD"),
	#     "HOST": env("MARIADB_HOST", default="127.0.0.1"),
	#     "PORT": env("MARIADB_PORT", default="5000")
#     }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
