# Generated by Django 5.1.4 on 2025-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresses', '0002_progresses_distance_from_goal_kvi_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresses',
            name='occurence_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
