# Generated by Django 5.1.4 on 2025-01-10 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KviTypes',
            fields=[
                ('kvi_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('kvi_type_name', models.CharField(max_length=20)),
                ('kvi_description', models.CharField(blank=True, max_length=40, null=True)),
                ('kvi_multiplier', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
            options={
                'db_table': 'kvi_types',
            },
        ),
    ]
