# Generated by Django 5.1.4 on 2025-01-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvi_types', '0002_alter_kvitypes_kvi_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvitypes',
            name='kvi_type_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kvi_type', to='users.appusers'),
        ),
        migrations.AddConstraint(
            model_name='kvitypes',
            constraint=models.UniqueConstraint(fields=('kvi_type_name', 'kvi_type_user'), name='unique_kvi_type_per_user'),
        ),
    ]
