# Generated by Django 5.1.4 on 2025-01-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0003_alter_habits_habit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('times_completed', models.IntegerField(default=0)),
                ('streak_length', models.IntegerField(default=0)),
                ('last_completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit_analytics', to='habits.habits')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
    ]
