# Generated by Django 5.1.4 on 2025-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('habits', '0002_alter_habits_habit_name_habits_unique_habit_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('habit_id', 'analytics_id'), name='unique_analytics_per_habit'),
        ),
    ]
