# Generated by Django 5.1.4 on 2025-01-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('habits', '0003_alter_habits_habit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='habit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit_analytics', to='habits.habits', unique=True),
        ),
    ]
