# Generated by Django 5.1.4 on 2025-01-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analytics_habit_id'),
        ('habits', '0003_alter_habits_habit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='habit_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_analytics', to='habits.habits'),
        ),
    ]
